#!/bin/bash

site_name=$1

if [ "$site_name" == "" ]
then
	printf "Please enter a name for the site.\nE.g. 'example.com'\n"
	return
fi

conf_file_name="/etc/apache2/sites-available/$site_name.conf"
conf_file_content="<VirtualHost *:80>\nServerName local.$1\nServerAlias local.$1\nServerAdmin webmaster@$1\nDocumentRoot /var/www/$1/public\nErrorLog ${APACHE_LOG_DIR}/error.log\nCustomLog ${APACHE_LOG_DIR}/access.log combined\n</VirtualHost>"

sudo mkdir -p /var/www/$site_name/public #Create site directory
sudo chown $USER:$USER /var/www/$site_name #Set directory ownership to the current user
sudo touch $conf_file_name #Create .conf file
echo -e $conf_file_content | sudo tee $conf_file_name #Add content to conf file
sudo a2ensite $site_name.conf
sudo systemctl reload apache2
echo -e "\n127.0.0.1	local.$site_name" | sudo tee -a /etc/hosts #Append to hosts file

echo -e "\nSite '$site_name' created.\nAccess it at local.$site_name"